{
 "title": "Immich",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization{system_memory_state=\"used\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_utilization{job=\"immich\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Thumbnail Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_thumbnail_generation_active{instance=\"ix-immich-server-1:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fascial Recognition Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_facial_recognition_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_metadata_extraction_active{job=\"immich\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_smart_search_active{job=\"immich\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Background Tasks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_background_task_active{job=\"immich\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplication Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_queues_duplicate_detection_active{job=\"immich\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}