{
 "title": "Jellyfin",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_sessions_count_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clients",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client) (jellyfin_sessions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_active_streams_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Shows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_item_counts{type=\"SeriesCount\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_item_counts{type=\"MovieCount\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}